name: Build APK

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

      # تحميل ملفات المشروع
      - name: Checkout
        uses: actions/checkout@v4


      # Python 3.14
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"


      # Java 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      # تثبيت متطلبات النظام
      - name: Install system dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            git \
            zip \
            unzip \
            build-essential \
            ccache \
            python3-dev \
            autoconf \
            automake \
            autopoint \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev \
            gettext \
            rustc \
            cargo


      # تثبيت Buildozer والمتطلبات
      - name: Install Buildozer dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install legacy-cgi setuptools
          python -m pip install "cython==0.29.34"
          python -m pip install git+https://github.com/kivy/buildozer.git


      # تنظيف أي ملفات بناء قديمة
      - name: Clean Buildozer
        run: |
          rm -rf ~/.buildozer
          rm -rf .buildozer
          rm -rf bin


      # بناء APK
      - name: Build APK
        run: |
          buildozer -v android debug


      # رفع APK كملف قابل للتحميل
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VoiceControl-APK
          path: bin/*.apk
          if-no-files-found: error
